export const customerResponse = {
  "statusCode": 200,
  "data": {
    "customerDetailsList": [
      {
        "customerid": 76,
        "companyid": 200,
        "companyname": "bingo pvt ltd",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dfff",
        "lastname": "fsfdsdsf",
        "email": "superadmissn@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 75,
        "companyid": 199,
        "companyname": "Kurkure ",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "jadgalee",
        "email": "superaxxdmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 74,
        "companyid": 197,
        "companyname": "puytrr",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dddd",
        "lastname": "dddd",
        "email": "supeddddradmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 73,
        "companyid": 196,
        "companyname": "puytrr",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "ttryyuyt",
        "lastname": "fsfdsdsf",
        "email": "superaiuiuiudmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 72,
        "companyid": 195,
        "companyname": "puytrr",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "ttryyuyt",
        "lastname": "jadgaleeassa",
        "email": "superaaaaaaadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 71,
        "companyid": 194,
        "companyname": "puytrr",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "ttryyuyt",
        "lastname": "fsfdsdsf",
        "email": "supuuueradmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 70,
        "companyid": 192,
        "companyname": "ww",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "fsfdsdsf",
        "email": "superssadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 69,
        "companyid": 191,
        "companyname": "wee",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "ttryyuyt",
        "lastname": "fsfdsdsf",
        "email": "supereeadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 68,
        "companyid": 189,
        "companyname": "saisystem",
        "userid": 0,
        "userroleid": 2,
        "title": "UI de",
        "firstname": "Sai",
        "lastname": "bindu",
        "email": "superrradmin@gmail.com",
        "phonenumber": "98766732",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 67,
        "companyid": 184,
        "companyname": "rrr",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dardda",
        "lastname": "jadgalee",
        "email": "suttperadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 66,
        "companyid": 183,
        "companyname": "dad",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "ffdggfh",
        "email": "supeeeeradmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 65,
        "companyid": 182,
        "companyname": "dsadsad",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dardda",
        "lastname": "jadgalee",
        "email": "aadss@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 64,
        "companyid": 181,
        "companyname": "ass",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "ffdggfh",
        "email": "aasss@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 63,
        "companyid": 180,
        "companyname": "puytrr",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dardda",
        "lastname": "ffd",
        "email": "aasppps@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 62,
        "companyid": 174,
        "companyname": "www",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "ffdggfh",
        "email": "aaewsedss@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 61,
        "companyid": 173,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "w    ",
        "firstname": "www",
        "lastname": "www",
        "email": "supewqeradmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 60,
        "companyid": 171,
        "companyname": "alfa company",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "alfa",
        "lastname": "a",
        "email": "alfddda@gmail.com",
        "phonenumber": "234758",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 59,
        "companyid": 169,
        "companyname": "alfa company",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "alfa",
        "lastname": "a",
        "email": "alfa@gmail.com",
        "phonenumber": "234758",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 58,
        "companyid": 165,
        "companyname": "asd",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "eerrr",
        "lastname": "fsfdsdsf",
        "email": "superadfcdmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 57,
        "companyid": 164,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "dsfds",
        "firstname": "ttryyuyt",
        "lastname": "fsfdsdsf",
        "email": "superadmin@gmail.com",
        "phonenumber": "11111111111111111111",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 56,
        "companyid": 163,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "superadmins@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 55,
        "companyid": 162,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dfff",
        "lastname": "fsfdsdsf",
        "email": "chrsssistop@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 54,
        "companyid": 161,
        "companyname": "qwee",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dfff",
        "lastname": "fffff",
        "email": "sfurajK@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 53,
        "companyid": 160,
        "companyname": "pomanss",
        "userid": 0,
        "userroleid": 2,
        "title": "fredr",
        "firstname": "rrrrrr",
        "lastname": "gfrtyu",
        "email": "waass@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 52,
        "companyid": 159,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "ttryyuyt",
        "lastname": "ffd",
        "email": "suwwwrajK@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 51,
        "companyid": 157,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "dsfds",
        "firstname": "archana",
        "lastname": "ffdgfg",
        "email": "adererermin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 50,
        "companyid": 156,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "wwww",
        "email": "suwperadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 49,
        "companyid": 155,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "supderadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 48,
        "companyid": 154,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "superggadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 47,
        "companyid": 153,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sussperadmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 46,
        "companyid": 152,
        "companyname": "Evolutionary Engineers Pvt Ltd.",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Iswa",
        "lastname": "Rao",
        "email": "raoiswa@gmail.com",
        "phonenumber": "234758",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 45,
        "companyid": 84,
        "companyname": "Schaefer LLC",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Mark",
        "lastname": "Wood",
        "email": "venkatakota@hotmail.com",
        "phonenumber": "2032789490",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 42,
        "companyid": 151,
        "companyname": "Nyra International Pvt Ltd",
        "userid": 0,
        "userroleid": 2,
        "title": "Mrs  ",
        "firstname": "Nyra",
        "lastname": "Y",
        "email": "nyra1@gmail.com",
        "phonenumber": "12345678",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 41,
        "companyid": 2,
        "companyname": "Bandcamp",
        "userid": 0,
        "userroleid": 0,
        "title": "Mrs  ",
        "firstname": "Nyra",
        "lastname": "Jadhav",
        "email": "nyra@gmail.com",
        "phonenumber": "7689341090",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 40,
        "companyid": 149,
        "companyname": "saisystem technology",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "zanzane",
        "email": "supessradmin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 39,
        "companyid": 148,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "aeeeeaass@gmial.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 38,
        "companyid": 147,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "admain@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 37,
        "companyid": 146,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "zanzane",
        "email": "admin@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 36,
        "companyid": 145,
        "companyname": "saisystem technology",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "zanzane",
        "email": "archanazanzane@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 35,
        "companyid": 134,
        "companyname": "fdfdfd",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "susdhagar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 34,
        "companyid": 133,
        "companyname": "dffdgfd",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "admin",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 33,
        "companyid": 132,
        "companyname": "dsfdsf",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "jadgalee",
        "email": "sudhadgar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 32,
        "companyid": 131,
        "companyname": "ddd",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhargar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 31,
        "companyid": 130,
        "companyname": "ADSD",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhagar@yorpmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 30,
        "companyid": 129,
        "companyname": "sfdgf",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "christop@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 29,
        "companyid": 128,
        "companyname": "FDFGF",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhagard@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 28,
        "companyid": 127,
        "companyname": "dgfdg",
        "userid": 0,
        "userroleid": 2,
        "title": "gfdgd",
        "firstname": "ggg",
        "lastname": "gfdgg",
        "email": "sudhagar@yopfmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 27,
        "companyid": 126,
        "companyname": "fdsf",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfsf",
        "firstname": "fsdgs",
        "lastname": "sdgsd",
        "email": "abc@gmail.com",
        "phonenumber": "453546575",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 26,
        "companyid": 125,
        "companyname": "dddd",
        "userid": 0,
        "userroleid": 2,
        "title": "dsafa",
        "firstname": "ssss",
        "lastname": "asda",
        "email": "assss@gmail.com",
        "phonenumber": "32423554",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 25,
        "companyid": 124,
        "companyname": "sss",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfs ",
        "firstname": "sdfsf",
        "lastname": "sdfs",
        "email": "abs@gmail.com",
        "phonenumber": "56677722",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 24,
        "companyid": 123,
        "companyname": "djkj",
        "userid": 0,
        "userroleid": 2,
        "title": "sfds ",
        "firstname": "sfsd",
        "lastname": "sgdsg",
        "email": "ddd@gmail.com",
        "phonenumber": "3454432211",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 23,
        "companyid": 122,
        "companyname": "ddsfdg",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhragar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 22,
        "companyid": 121,
        "companyname": "ffdgg",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhagfar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 21,
        "companyid": 120,
        "companyname": "fffdgfd",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "sfh",
        "lastname": "ffd",
        "email": "sudhagadr@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 20,
        "companyid": 119,
        "companyname": "ddda",
        "userid": 0,
        "userroleid": 2,
        "title": "sdfh ",
        "firstname": "ttryyuyt",
        "lastname": "ffdggfh",
        "email": "sudhafgar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 19,
        "companyid": 118,
        "companyname": "saisystem",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "zanzane",
        "email": "sudhagare@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 18,
        "companyid": 117,
        "companyname": "SaiSystems",
        "userid": 0,
        "userroleid": 2,
        "title": "UI De",
        "firstname": "Sai",
        "lastname": "Bindu",
        "email": "test111@gmail.com",
        "phonenumber": "98765432267",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 17,
        "companyid": 116,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "jadgalee",
        "email": "sai1@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 16,
        "companyid": 115,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "react",
        "firstname": "archana",
        "lastname": "jadgalee",
        "email": "sai@gmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 15,
        "companyid": 114,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "fggfh",
        "firstname": "dardda",
        "lastname": "zanzane",
        "email": "sudhagar@yopmail.com",
        "phonenumber": "21334355",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 14,
        "companyid": 113,
        "companyname": "string",
        "userid": 0,
        "userroleid": 2,
        "title": "strin",
        "firstname": "string",
        "lastname": "string",
        "email": "string",
        "phonenumber": "string",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 13,
        "companyid": 112,
        "companyname": "Safari",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Pritesh",
        "lastname": "Bhargwa",
        "email": "pritesh@gmail.com",
        "phonenumber": "23682379",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 12,
        "companyid": 118,
        "companyname": "saisystem",
        "userid": 0,
        "userroleid": 2,
        "title": "Mrs  ",
        "firstname": "Uma",
        "lastname": "kurasi",
        "email": "uma2@gmail.com",
        "phonenumber": "38293102",
        "address": "AB ROad Mumbai",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 10,
        "companyid": 118,
        "companyname": "saisystem",
        "userid": 0,
        "userroleid": 2,
        "title": "mrs  ",
        "firstname": "Deepika",
        "lastname": "padukone",
        "email": "deepika@gmail.com",
        "phonenumber": "32322345357",
        "address": "",
        "zipcode": "2345633",
        "cityid": 7,
        "cityname": "Graysville",
        "stateid": 7,
        "statename": "Connecticut",
        "countryid": 1,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 9,
        "companyid": 118,
        "companyname": "saisystem",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Ranveer",
        "lastname": "singh",
        "email": "Ranveer@gmail.com",
        "phonenumber": "67667745357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 8,
        "companyid": 117,
        "companyname": "SaiSystems",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "joho",
        "lastname": "xing",
        "email": "joho@gmail.com",
        "phonenumber": "09877645357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 7,
        "companyid": 117,
        "companyname": "SaiSystems",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "zala",
        "lastname": "leon",
        "email": "zala@gmail.com",
        "phonenumber": "6576745357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 6,
        "companyid": 116,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Zebar",
        "lastname": "phon",
        "email": "zebar@gmail.com",
        "phonenumber": "09877645357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 5,
        "companyid": 116,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Eliaj",
        "lastname": "son",
        "email": "Eliaj@gmail.com",
        "phonenumber": "6576745357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 3,
        "companyid": 115,
        "companyname": "sai",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Rhino",
        "lastname": "Asam",
        "email": "Rhino@gmail.com",
        "phonenumber": "6576745357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 2,
        "companyid": 114,
        "companyname": "archana",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "kesahv",
        "lastname": "smith",
        "email": "kesahv@gmail.com",
        "phonenumber": "987645357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      },
      {
        "customerid": 1,
        "companyid": 113,
        "companyname": "string",
        "userid": 0,
        "userroleid": 2,
        "title": "Mr   ",
        "firstname": "Roby",
        "lastname": "july",
        "email": "roby@gmail.com",
        "phonenumber": "987645357",
        "address": "",
        "zipcode": "",
        "cityid": 0,
        "cityname": "",
        "stateid": 0,
        "statename": "",
        "countryid": 0,
        "countryname": "US",
        "isactive": true
      }
    ],
    "totalRows": 72
  },
  "status": "Success",
  "message": "Customer get List API requested"
}