export const usersResponse = {
  "statusCode": 200,
  "data": {
    "userList": [
      {
        "userId": 51,
        "prefix": null,
        "firstname": "Adrianna",
        "middlename": "c",
        "lastname": "Konopelski",
        "username": "Leann.Thompson",
        "password": null,
        "email": "Keith.Ondricka@hotmail.com",
        "phonenumber": "8827019875",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/karalek_128.jpg",
        "profileFile": null
      },
      {
        "userId": 64,
        "prefix": null,
        "firstname": "Aisha",
        "middlename": "a",
        "lastname": "Hickle",
        "username": "Foster59",
        "password": null,
        "email": "Amaya_Purdy@gmail.com",
        "phonenumber": "9635536425",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/tom_even_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14059,
        "prefix": null,
        "firstname": "Alen",
        "middlename": "",
        "lastname": "Turing",
        "username": "",
        "password": null,
        "email": "at@gmail.com",
        "phonenumber": "6280876575",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14055,
        "prefix": null,
        "firstname": "Alex",
        "middlename": "",
        "lastname": "Ngs",
        "username": "",
        "password": null,
        "email": "an@gmail.com",
        "phonenumber": "8029323233",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14080,
        "prefix": null,
        "firstname": "alfa",
        "middlename": "",
        "lastname": "a",
        "username": "",
        "password": null,
        "email": "alfa@gmail.com",
        "phonenumber": "234758",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14082,
        "prefix": null,
        "firstname": "alfa",
        "middlename": "",
        "lastname": "a",
        "username": "",
        "password": null,
        "email": "alfddda@gmail.com",
        "phonenumber": "234758",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 11,
        "prefix": null,
        "firstname": "Alfredo",
        "middlename": "c",
        "lastname": "Zulauf",
        "username": "Guillermo0",
        "password": null,
        "email": "Deja_Dietrich@hotmail.com",
        "phonenumber": "9754785267",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/11/ProfilePhoto/Ame_pic.png",
        "profileFile": null
      },
      {
        "userId": 13974,
        "prefix": null,
        "firstname": "Alice",
        "middlename": "",
        "lastname": "Colin",
        "username": "",
        "password": null,
        "email": "colin.alice@gmail.com",
        "phonenumber": "7545212356",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 44,
        "prefix": null,
        "firstname": "Alvina",
        "middlename": "a",
        "lastname": "Rodriguez",
        "username": "Shanna.Kuhn19",
        "password": null,
        "email": "Agustina.Schinner@yahoo.com",
        "phonenumber": "8921378544",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/conspirator_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14056,
        "prefix": null,
        "firstname": "Amar",
        "middlename": "",
        "lastname": "Candidateone",
        "username": "",
        "password": null,
        "email": "candidate1@gmail.com",
        "phonenumber": "37462734",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14044,
        "prefix": null,
        "firstname": "Amar",
        "middlename": "",
        "lastname": "Yelmar",
        "username": "",
        "password": null,
        "email": "amar1@gmail.com",
        "phonenumber": "(848) 484-8848",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14047,
        "prefix": null,
        "firstname": "Amar",
        "middlename": "",
        "lastname": "Yelmar",
        "username": "",
        "password": null,
        "email": "amar2@gmail.com",
        "phonenumber": "8805075431",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14118,
        "prefix": null,
        "firstname": "Amaran",
        "middlename": "",
        "lastname": "Ns",
        "username": "",
        "password": null,
        "email": "amaran@gmail.com",
        "phonenumber": "1234569857",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/14118/ProfilePhoto/9CE19559-FC52-4DB8-96F0-9C9C2263FE37.jpg",
        "profileFile": null
      },
      {
        "userId": 14045,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "supessradmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14038,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "archanazanzane@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14039,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "admin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14068,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "ffdgfg",
        "username": "",
        "password": null,
        "email": "adererermin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13984,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "archanazanzane3000@gmail.com",
        "phonenumber": "9503416000",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14006,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "sai@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14007,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "sai1@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14009,
        "prefix": null,
        "firstname": "archana",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhagare@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13985,
        "prefix": null,
        "firstname": "Ava",
        "middlename": "",
        "lastname": "W",
        "username": "",
        "password": null,
        "email": "ert@yopmail.com",
        "phonenumber": "(123) 524-1526",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 72,
        "prefix": null,
        "firstname": "Bernadine",
        "middlename": "a",
        "lastname": "Braun",
        "username": "Sonya_Orn45",
        "password": null,
        "email": "Toni_Torphy69@gmail.com",
        "phonenumber": "7370532759",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/karsh_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14110,
        "prefix": null,
        "firstname": "Bindu",
        "middlename": "",
        "lastname": "Raavi",
        "username": "",
        "password": null,
        "email": "bindu@gmail.com",
        "phonenumber": "(987)-654-5453",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 32,
        "prefix": null,
        "firstname": "Camren",
        "middlename": "b",
        "lastname": "Schiller",
        "username": "Minerva.Willms36",
        "password": null,
        "email": "Yasmin.Mante@hotmail.com",
        "phonenumber": "9288325201",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/eduardostuart_128.jpg",
        "profileFile": null
      },
      {
        "userId": 76,
        "prefix": null,
        "firstname": "Coleman",
        "middlename": "b",
        "lastname": "Ritchie",
        "username": "Virginia52",
        "password": null,
        "email": "Lavonne24@yahoo.com",
        "phonenumber": "7995138207",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/h1brd_128.jpg",
        "profileFile": null
      },
      {
        "userId": 42,
        "prefix": null,
        "firstname": "Colin",
        "middlename": "c",
        "lastname": "Hirthe",
        "username": "Rhett53",
        "password": null,
        "email": "Jaida84@hotmail.com",
        "phonenumber": "8327720687",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/andrewofficer_128.jpg",
        "profileFile": null
      },
      {
        "userId": 15,
        "prefix": null,
        "firstname": "Colt",
        "middlename": "a",
        "lastname": "Ernser",
        "username": "Addison_Heathcote68",
        "password": null,
        "email": "Mitchel_Carroll@gmail.com",
        "phonenumber": "7455213174",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/carlyson_128.jpg",
        "profileFile": null
      },
      {
        "userId": 46,
        "prefix": null,
        "firstname": "Curt",
        "middlename": "b",
        "lastname": "Braun",
        "username": "Lilian.Simonis21",
        "password": null,
        "email": "Agustin_Cartwright49@hotmail.com",
        "phonenumber": "7009180463",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/lmjabreu_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14005,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhagar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14012,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhagfar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14013,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhragar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14064,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sussperadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14065,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "superggadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14066,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "supderadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14067,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "wwww",
        "username": "",
        "password": null,
        "email": "suwperadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14021,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhagard@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14022,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "christop@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14023,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhagar@yorpmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14024,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "sudhargar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14025,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "sudhadgar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14026,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "admin",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14027,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "susdhagar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14041,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "admain@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14042,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "aeeeeaass@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14098,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "superssadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14074,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "zanzane",
        "username": "",
        "password": null,
        "email": "superadmins@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14085,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "ffdggfh",
        "username": "",
        "password": null,
        "email": "aaewsedss@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14086,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "ffd",
        "username": "",
        "password": null,
        "email": "aasppps@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14087,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "ffdggfh",
        "username": "",
        "password": null,
        "email": "aasss@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14088,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "aadss@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14089,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "ffdggfh",
        "username": "",
        "password": null,
        "email": "supeeeeradmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14090,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "suttperadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14114,
        "prefix": null,
        "firstname": "dardda",
        "middlename": "",
        "lastname": "jadgalee",
        "username": "",
        "password": null,
        "email": "superaxxdmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14113,
        "prefix": null,
        "firstname": "dddd",
        "middlename": "",
        "lastname": "dddd",
        "username": "",
        "password": null,
        "email": "supeddddradmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14040,
        "prefix": null,
        "firstname": "Deepika",
        "middlename": "",
        "lastname": "Pai",
        "username": "",
        "password": null,
        "email": "dp@gmail.com",
        "phonenumber": "7647255361",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13970,
        "prefix": null,
        "firstname": "Deepika",
        "middlename": "",
        "lastname": "padukone",
        "username": "",
        "password": null,
        "email": "deepika@gmail.com",
        "phonenumber": "32322345357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14072,
        "prefix": null,
        "firstname": "dfff",
        "middlename": "",
        "lastname": "fffff",
        "username": "",
        "password": null,
        "email": "sfurajK@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14073,
        "prefix": null,
        "firstname": "dfff",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "chrsssistop@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14115,
        "prefix": null,
        "firstname": "dfff",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "superadmissn@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14076,
        "prefix": null,
        "firstname": "eerrr",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "superadfcdmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13964,
        "prefix": null,
        "firstname": "Ele",
        "middlename": "",
        "lastname": "phent",
        "username": "",
        "password": null,
        "email": "ele@gmail.com",
        "phonenumber": "09877645357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 20,
        "prefix": null,
        "firstname": "Eleanore",
        "middlename": "b",
        "lastname": "Wintheiser",
        "username": "Marcelino_Abshire87",
        "password": null,
        "email": "Gladyce.Lemke77@yahoo.com",
        "phonenumber": "9580270899",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/20/ProfilePhoto/ame1_pic.png",
        "profileFile": null
      },
      {
        "userId": 13965,
        "prefix": null,
        "firstname": "Eliaj",
        "middlename": "",
        "lastname": "son",
        "username": "",
        "password": null,
        "email": "Eliaj@gmail.com",
        "phonenumber": "6576745357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 63,
        "prefix": null,
        "firstname": "Elisa",
        "middlename": "a",
        "lastname": "Stamm",
        "username": "May-55",
        "password": null,
        "email": "Deja_Wiza@yahoo.com",
        "phonenumber": "7073377806",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/dc_user_128.jpg",
        "profileFile": null
      },
      {
        "userId": 78,
        "prefix": null,
        "firstname": "Elyssa",
        "middlename": "a",
        "lastname": "Smith",
        "username": "Brendon.Spencer1",
        "password": null,
        "email": "Manuela.Rodriguez@gmail.com",
        "phonenumber": "8707326887",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/charlesrpratt_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14017,
        "prefix": null,
        "firstname": "fsdgs",
        "middlename": "",
        "lastname": "sdgsd",
        "username": "",
        "password": null,
        "email": "abc@gmail.com",
        "phonenumber": "453546575",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14020,
        "prefix": null,
        "firstname": "ggg",
        "middlename": "",
        "lastname": "gfdgg",
        "username": "",
        "password": null,
        "email": "sudhagar@yopfmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 62,
        "prefix": null,
        "firstname": "Gino",
        "middlename": "a",
        "lastname": "Lind",
        "username": "Evangeline2",
        "password": null,
        "email": "Warren40@gmail.com",
        "phonenumber": "8607831287",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/sharvin_128.jpg",
        "profileFile": null
      },
      {
        "userId": 37,
        "prefix": null,
        "firstname": "Giovanna",
        "middlename": "b",
        "lastname": "Hammes",
        "username": "Guy_Gleichner",
        "password": null,
        "email": "Nasir.Wehner@yahoo.com",
        "phonenumber": "7419926336",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/gauchomatt_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14048,
        "prefix": null,
        "firstname": "Hari",
        "middlename": "",
        "lastname": "Ha",
        "username": "",
        "password": null,
        "email": "hari@gmail.com",
        "phonenumber": "6958696965",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 70,
        "prefix": null,
        "firstname": "Hector",
        "middlename": "b",
        "lastname": "Botsford",
        "username": "Dangelo.Gerlach7",
        "password": null,
        "email": "Darwin_Daugherty@gmail.com",
        "phonenumber": "7835264592",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/herrhaase_128.jpg",
        "profileFile": null
      },
      {
        "userId": 45,
        "prefix": null,
        "firstname": "Horacio",
        "middlename": "c",
        "lastname": "Herman",
        "username": "Juliana_Ruecker7",
        "password": null,
        "email": "Brant_Cummings1@gmail.com",
        "phonenumber": "9158924306",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/adamnac_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13982,
        "prefix": null,
        "firstname": "Isabella",
        "middlename": "",
        "lastname": "Johnson",
        "username": "",
        "password": null,
        "email": "ravi1@gmail.com",
        "phonenumber": "(123) 456-7843",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14060,
        "prefix": null,
        "firstname": "Iswa",
        "middlename": "",
        "lastname": "Rao",
        "username": "",
        "password": null,
        "email": "raoiswa@gmail.com",
        "phonenumber": "234758",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 24,
        "prefix": null,
        "firstname": "Jalon",
        "middlename": "c",
        "lastname": "Volkman",
        "username": "Maximilian7",
        "password": null,
        "email": "Leta_Hauck@yahoo.com",
        "phonenumber": "9943447976",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/stalewine_128.jpg",
        "profileFile": null
      },
      {
        "userId": 68,
        "prefix": null,
        "firstname": "Jamil",
        "middlename": "b",
        "lastname": "Terry",
        "username": "Mittie.Kovacek43",
        "password": null,
        "email": "Casandra6@gmail.com",
        "phonenumber": "7075672512",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/AlbertoCococi_128.jpg",
        "profileFile": null
      },
      {
        "userId": 73,
        "prefix": null,
        "firstname": "Joany",
        "middlename": "c",
        "lastname": "Shields",
        "username": "Nyah_Spinka77",
        "password": null,
        "email": "Beaulah_Lockman@hotmail.com",
        "phonenumber": "7111311962",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/gojeanyn_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14052,
        "prefix": null,
        "firstname": "John",
        "middlename": "",
        "lastname": "Brown",
        "username": "",
        "password": null,
        "email": "johnb@gmail.com",
        "phonenumber": "8147901456",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13995,
        "prefix": null,
        "firstname": "John",
        "middlename": "",
        "lastname": "Lees",
        "username": "",
        "password": null,
        "email": "johnlee@gmail.com",
        "phonenumber": "124567896548",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13,
        "prefix": null,
        "firstname": "Johnathon",
        "middlename": "c",
        "lastname": "Hayes",
        "username": "Camilla79",
        "password": null,
        "email": "Jimmy.Mills72@yahoo.com",
        "phonenumber": "8808072307",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/gonzalorobaina_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13968,
        "prefix": null,
        "firstname": "joho",
        "middlename": "",
        "lastname": "xing",
        "username": "",
        "password": null,
        "email": "joho@gmail.com",
        "phonenumber": "09877645357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14053,
        "prefix": null,
        "firstname": "Jon",
        "middlename": "",
        "lastname": "Bravo",
        "username": "",
        "password": null,
        "email": "jonb@gmail.com",
        "phonenumber": "2567854320",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 66,
        "prefix": null,
        "firstname": "Justen",
        "middlename": "c",
        "lastname": "Berge",
        "username": "Thelma.Turner12",
        "password": null,
        "email": "Wyatt_Hyatt@yahoo.com",
        "phonenumber": "7391612321",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/emileboudeling_128.jpg",
        "profileFile": null
      },
      {
        "userId": 79,
        "prefix": null,
        "firstname": "Kaelyn",
        "middlename": "b",
        "lastname": "Turcotte",
        "username": "Freda.Wolf20",
        "password": null,
        "email": "Jerod.Bergstrom71@yahoo.com",
        "phonenumber": "8175670694",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/psdesignuk_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13993,
        "prefix": null,
        "firstname": "Kajal",
        "middlename": "",
        "lastname": "More",
        "username": "",
        "password": null,
        "email": "kjl@gmial.com",
        "phonenumber": "8888888888",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13998,
        "prefix": null,
        "firstname": "Kajal",
        "middlename": "",
        "lastname": "More",
        "username": "",
        "password": null,
        "email": "aass@gmial.com",
        "phonenumber": "8888888888",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13999,
        "prefix": null,
        "firstname": "Kajal",
        "middlename": "",
        "lastname": "More",
        "username": "",
        "password": null,
        "email": "kajalmore31@gmail.com",
        "phonenumber": "8723928394",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14058,
        "prefix": null,
        "firstname": "Kalyani",
        "middlename": "",
        "lastname": "Kairnar",
        "username": "",
        "password": null,
        "email": "kalyani@tech.saisystems.com",
        "phonenumber": "(798)-936-3324_",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/14058/ProfilePhoto/profile.png",
        "profileFile": null
      },
      {
        "userId": 13979,
        "prefix": null,
        "firstname": "Kalyani",
        "middlename": "",
        "lastname": "Kairnar",
        "username": "",
        "password": null,
        "email": "kalyani@gmail.com",
        "phonenumber": "9876543212",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 71,
        "prefix": null,
        "firstname": "Karlie",
        "middlename": "a",
        "lastname": "Gutmann",
        "username": "Antone26",
        "password": null,
        "email": "Vernie.Beer86@gmail.com",
        "phonenumber": "7112365133",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/dnezkumar_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13962,
        "prefix": null,
        "firstname": "kesahv",
        "middlename": "",
        "lastname": "smith",
        "username": "",
        "password": null,
        "email": "kesahv@gmail.com",
        "phonenumber": "987645357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13991,
        "prefix": null,
        "firstname": "Keshav",
        "middlename": "",
        "lastname": "Kori",
        "username": "",
        "password": null,
        "email": "keshav@gmial.com",
        "phonenumber": "9999999",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13997,
        "prefix": null,
        "firstname": "Keshav",
        "middlename": "",
        "lastname": "Rao",
        "username": "",
        "password": null,
        "email": "Keshavrao9@gmail.com",
        "phonenumber": "8029323233",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 22,
        "prefix": null,
        "firstname": "Keyshawn",
        "middlename": "b",
        "lastname": "Rau",
        "username": "Ciara_Kuvalis",
        "password": null,
        "email": "Marlin.Heathcote95@hotmail.com",
        "phonenumber": "9446991514",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/matkins_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14000,
        "prefix": null,
        "firstname": "KJL",
        "middlename": "",
        "lastname": "MRB",
        "username": "",
        "password": null,
        "email": "kjl@gmail.com",
        "phonenumber": "1234567890",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14050,
        "prefix": null,
        "firstname": "Labina",
        "middlename": "",
        "lastname": "Sen",
        "username": "",
        "password": null,
        "email": "labinasen@gmail.com",
        "phonenumber": "9876644444",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 59,
        "prefix": null,
        "firstname": "Lesly",
        "middlename": "b",
        "lastname": "Olson",
        "username": "Eunice52",
        "password": null,
        "email": "Name_Frami@gmail.com",
        "phonenumber": "7883865020",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/petebernardo_128.jpg",
        "profileFile": null
      },
      {
        "userId": 27,
        "prefix": null,
        "firstname": "Letha",
        "middlename": "a",
        "lastname": "Medhurst",
        "username": "Alfred_Considine5",
        "password": null,
        "email": "Peter78@yahoo.com",
        "phonenumber": "8579062191",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/slowspock_128.jpg",
        "profileFile": null
      },
      {
        "userId": 29,
        "prefix": null,
        "firstname": "Lorna",
        "middlename": "c",
        "lastname": "Feeney",
        "username": "Mary.Koelpin79",
        "password": null,
        "email": "Jasen.Hirthe13@gmail.com",
        "phonenumber": "8457162204",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/therealmarvin_128.jpg",
        "profileFile": null
      },
      {
        "userId": 36,
        "prefix": null,
        "firstname": "Lucius",
        "middlename": "b",
        "lastname": "Murazik",
        "username": "Osvaldo.Streich63",
        "password": null,
        "email": "Johnathon_Cassin@hotmail.com",
        "phonenumber": "8028980087",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/nckjrvs_128.jpg",
        "profileFile": null
      },
      {
        "userId": 81,
        "prefix": null,
        "firstname": "Mark",
        "middlename": "kk",
        "lastname": "Wood",
        "username": "",
        "password": null,
        "email": "wood.mark@gmail.com",
        "phonenumber": "543216789",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14001,
        "prefix": null,
        "firstname": "Mass",
        "middlename": "",
        "lastname": "Bos",
        "username": "",
        "password": null,
        "email": "massb@gmail.com",
        "phonenumber": "1112223339",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 77,
        "prefix": null,
        "firstname": "Maybell",
        "middlename": "c",
        "lastname": "Brakus",
        "username": "Garry.Stanton",
        "password": null,
        "email": "Karlee31@hotmail.com",
        "phonenumber": "8129984065",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/chanpory_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14019,
        "prefix": null,
        "firstname": "Mobile",
        "middlename": "",
        "lastname": "Mob",
        "username": "",
        "password": null,
        "email": "candidate@gmail.com",
        "phonenumber": "8574541257",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 28,
        "prefix": null,
        "firstname": "Monique",
        "middlename": "b",
        "lastname": "Lind",
        "username": "Brennan_Kemmer",
        "password": null,
        "email": "Cara41@yahoo.com",
        "phonenumber": "8599813858",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/maximsorokin_128.jpg",
        "profileFile": null
      },
      {
        "userId": 16,
        "prefix": null,
        "firstname": "Nakia",
        "middlename": "c",
        "lastname": "Kertzmann",
        "username": "Robyn_Bernhard2",
        "password": null,
        "email": "Felton18@hotmail.com",
        "phonenumber": "9516219352",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/jydesign_128.jpg",
        "profileFile": null
      },
      {
        "userId": 69,
        "prefix": null,
        "firstname": "Nels",
        "middlename": "a",
        "lastname": "Connelly",
        "username": "Daren_Runte",
        "password": null,
        "email": "Noe57@yahoo.com",
        "phonenumber": "8613736285",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/muringa_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13996,
        "prefix": null,
        "firstname": "Nikhil",
        "middlename": "",
        "lastname": "Deshpande",
        "username": "",
        "password": null,
        "email": "nikhildesh11@gmail.com",
        "phonenumber": "8658709008",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14051,
        "prefix": null,
        "firstname": "Nyra",
        "middlename": "",
        "lastname": "Y",
        "username": "",
        "password": null,
        "email": "nyra1@gmail.com",
        "phonenumber": "12345678",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14049,
        "prefix": null,
        "firstname": "Nyra",
        "middlename": "",
        "lastname": "Jadhav",
        "username": "",
        "password": null,
        "email": "nyra@gmail.com",
        "phonenumber": "7689341090",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14061,
        "prefix": null,
        "firstname": "Panther",
        "middlename": "",
        "lastname": "Admin",
        "username": "",
        "password": null,
        "email": "pantheradmin@gmail.com",
        "phonenumber": "",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 1,
        "prefix": null,
        "firstname": "Panther",
        "middlename": "",
        "lastname": "Group",
        "username": "Admin Panther Group",
        "password": null,
        "email": "adminpanther@gmail.com",
        "phonenumber": "0000000000",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 48,
        "prefix": null,
        "firstname": "Pierce",
        "middlename": "b",
        "lastname": "Prosacco",
        "username": "Jazmyn_Rempel76",
        "password": null,
        "email": "Elian_Krajcik@gmail.com",
        "phonenumber": "8667892471",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/danvernon_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14003,
        "prefix": null,
        "firstname": "Pritesh",
        "middlename": "",
        "lastname": "Bhargwa",
        "username": "",
        "password": null,
        "email": "pritesh@gmail.com",
        "phonenumber": "23682379",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13969,
        "prefix": null,
        "firstname": "Ranveer",
        "middlename": "",
        "lastname": "singh",
        "username": "",
        "password": null,
        "email": "Ranveer@gmail.com",
        "phonenumber": "67667745357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13981,
        "prefix": null,
        "firstname": "Rav",
        "middlename": "",
        "lastname": "Md",
        "username": "",
        "password": null,
        "email": "ravi@gmail.com",
        "phonenumber": "123 4567894",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 65,
        "prefix": null,
        "firstname": "Reynold",
        "middlename": "c",
        "lastname": "Wunsch",
        "username": "Stuart20",
        "password": null,
        "email": "Zachary.Bayer91@hotmail.com",
        "phonenumber": "7900824430",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/iamsteffen_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13963,
        "prefix": null,
        "firstname": "Rhino",
        "middlename": "",
        "lastname": "Asam",
        "username": "",
        "password": null,
        "email": "Rhino@gmail.com",
        "phonenumber": "6576745357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13961,
        "prefix": null,
        "firstname": "Roby",
        "middlename": "",
        "lastname": "july",
        "username": "",
        "password": null,
        "email": "roby@gmail.com",
        "phonenumber": "987645357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14071,
        "prefix": null,
        "firstname": "rrrrrr",
        "middlename": "",
        "lastname": "gfrtyu",
        "username": "",
        "password": null,
        "email": "waass@gmial.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14008,
        "prefix": null,
        "firstname": "Sai",
        "middlename": "",
        "lastname": "Bindu",
        "username": "",
        "password": null,
        "email": "test111@gmail.com",
        "phonenumber": "98765432267",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13989,
        "prefix": null,
        "firstname": "Sai",
        "middlename": "",
        "lastname": "Raavi",
        "username": "",
        "password": null,
        "email": "test1234@gmail.com",
        "phonenumber": "32432554456554666666",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13977,
        "prefix": null,
        "firstname": "Sai",
        "middlename": "",
        "lastname": "Bindu",
        "username": "",
        "password": null,
        "email": "sbraavi@tech.saisystems.com",
        "phonenumber": "9876543456",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14116,
        "prefix": null,
        "firstname": "Sai",
        "middlename": "",
        "lastname": "Raavi",
        "username": "",
        "password": null,
        "email": "bindu@saisystems.com",
        "phonenumber": "(897)-654-3256",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14095,
        "prefix": null,
        "firstname": "Sai",
        "middlename": "",
        "lastname": "bindu",
        "username": "",
        "password": null,
        "email": "superrradmin@gmail.com",
        "phonenumber": "98766732",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13960,
        "prefix": null,
        "firstname": "Sai Bindu",
        "middlename": "",
        "lastname": "Raavi",
        "username": "",
        "password": null,
        "email": "Mukesh.Seervi@gmail.com",
        "phonenumber": "(987)-654-32346",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13983,
        "prefix": null,
        "firstname": "Saloni",
        "middlename": "",
        "lastname": "Sharma",
        "username": "",
        "password": null,
        "email": "test@gmail.com",
        "phonenumber": "(565) 236-5233",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14002,
        "prefix": null,
        "firstname": "Sam",
        "middlename": "",
        "lastname": "Calif",
        "username": "",
        "password": null,
        "email": "samcalif@gmial.com",
        "phonenumber": "2223334449",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14018,
        "prefix": null,
        "firstname": "Sdf",
        "middlename": "",
        "lastname": "Sdf",
        "username": "",
        "password": null,
        "email": "sd@gmail.com",
        "phonenumber": "1511111178",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14015,
        "prefix": null,
        "firstname": "sdfsf",
        "middlename": "",
        "lastname": "sdfs",
        "username": "",
        "password": null,
        "email": "abs@gmail.com",
        "phonenumber": "56677722",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14011,
        "prefix": null,
        "firstname": "sfh",
        "middlename": "",
        "lastname": "ffd",
        "username": "",
        "password": null,
        "email": "sudhagadr@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14014,
        "prefix": null,
        "firstname": "sfsd",
        "middlename": "",
        "lastname": "sgdsg",
        "username": "",
        "password": null,
        "email": "ddd@gmail.com",
        "phonenumber": "3454432211",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13992,
        "prefix": null,
        "firstname": "Shabdali",
        "middlename": "",
        "lastname": "Deshpande",
        "username": "",
        "password": null,
        "email": "shabdalidesh9@gmail.com",
        "phonenumber": "11333343434",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 67,
        "prefix": null,
        "firstname": "Shana",
        "middlename": "c",
        "lastname": "Mante",
        "username": "Marc_Sanford42",
        "password": null,
        "email": "Emerald_Olson7@yahoo.com",
        "phonenumber": "7225983353",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/mandalareopens_128.jpg",
        "profileFile": null
      },
      {
        "userId": 17,
        "prefix": null,
        "firstname": "Sheridan",
        "middlename": "b",
        "lastname": "Hammes",
        "username": "Rachel_Dickinson",
        "password": null,
        "email": "Emerald.Johnson91@hotmail.com",
        "phonenumber": "7640284573",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/lisovsky_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13978,
        "prefix": null,
        "firstname": "Shriya",
        "middlename": "",
        "lastname": "Anand",
        "username": "",
        "password": null,
        "email": "shriya@gmail.com",
        "phonenumber": "9876543456",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13990,
        "prefix": null,
        "firstname": "Shriya candidate ",
        "middlename": "",
        "lastname": "Anand",
        "username": "",
        "password": null,
        "email": "testshriya@gmail.com",
        "phonenumber": "(124) 224-2424",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14054,
        "prefix": null,
        "firstname": "SRK",
        "middlename": "",
        "lastname": "Brab",
        "username": "",
        "password": null,
        "email": "srk@gmail.com",
        "phonenumber": "3456785431",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14016,
        "prefix": null,
        "firstname": "ssss",
        "middlename": "",
        "lastname": "asda",
        "username": "",
        "password": null,
        "email": "assss@gmail.com",
        "phonenumber": "32423554",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14004,
        "prefix": null,
        "firstname": "string",
        "middlename": "",
        "lastname": "string",
        "username": "",
        "password": null,
        "email": "string",
        "phonenumber": "string",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13975,
        "prefix": null,
        "firstname": "Sudfhar",
        "middlename": "",
        "lastname": "Mani",
        "username": "",
        "password": null,
        "email": "ravi@yopmail.com",
        "phonenumber": "451 2452541",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13976,
        "prefix": null,
        "firstname": "Sudhagar",
        "middlename": "",
        "lastname": "Amaran",
        "username": "",
        "password": null,
        "email": "sudhagar1@gmail.com",
        "phonenumber": "213 5471585",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13973,
        "prefix": null,
        "firstname": "sudhagar",
        "middlename": "string",
        "lastname": "amaran",
        "username": "",
        "password": null,
        "email": "sudhagar.amaran@gmail.com",
        "phonenumber": "string",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13994,
        "prefix": null,
        "firstname": "Sudhagar",
        "middlename": "",
        "lastname": "Nataraja",
        "username": "",
        "password": null,
        "email": "su123@yopmail.com",
        "phonenumber": "(123) 654-1252",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13980,
        "prefix": null,
        "firstname": "Sudhir",
        "middlename": "",
        "lastname": "Sudhagar",
        "username": "",
        "password": null,
        "email": "sud123@yopmail.com",
        "phonenumber": "1234567857",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/13980/ProfilePhoto/rn_image_picker_lib_temp_0858849b-7d04-41c4-86e4-6220deee2abd.jpg",
        "profileFile": null
      },
      {
        "userId": 2,
        "prefix": null,
        "firstname": "Suresh",
        "middlename": "",
        "lastname": "Kumar",
        "username": "SureshK",
        "password": null,
        "email": "sureshK@gmail.com",
        "phonenumber": "9999999990",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 7,
        "prefix": null,
        "firstname": "Suresh",
        "middlename": "k",
        "lastname": "Kumar",
        "username": "Corene33",
        "password": null,
        "email": "kumars@gmail.com",
        "phonenumber": "0000000000",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://sadeveastusa001.blob.core.windows.net/cndev-appdata-001/Users/7/ProfilePhoto/pic.jpg",
        "profileFile": null
      },
      {
        "userId": 61,
        "prefix": null,
        "firstname": "Terence",
        "middlename": "a",
        "lastname": "Abernathy",
        "username": "Weldon_Littel",
        "password": null,
        "email": "Valentine21@hotmail.com",
        "phonenumber": "8760628939",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/andresdjasso_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14117,
        "prefix": null,
        "firstname": "test",
        "middlename": "",
        "lastname": "test",
        "username": "",
        "password": null,
        "email": "candidatetest@gmail.com",
        "phonenumber": "(876)-754-5354",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 26,
        "prefix": null,
        "firstname": "Thaddeus",
        "middlename": "c",
        "lastname": "Keeling",
        "username": "Orval_Willms13",
        "password": null,
        "email": "Nina86@gmail.com",
        "phonenumber": "8574510424",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/phillapier_128.jpg",
        "profileFile": null
      },
      {
        "userId": 21,
        "prefix": null,
        "firstname": "Theodore",
        "middlename": "a",
        "lastname": "Marquardt",
        "username": "Martin80",
        "password": null,
        "email": "Willa.Walker@gmail.com",
        "phonenumber": "9463522658",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/tjrus_128.jpg",
        "profileFile": null
      },
      {
        "userId": 50,
        "prefix": null,
        "firstname": "Tobin",
        "middlename": "a",
        "lastname": "Willms",
        "username": "Orin.Daniel",
        "password": null,
        "email": "Velva.Leffler@yahoo.com",
        "phonenumber": "7123430810",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/stefanozoffoli_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14010,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "ffdggfh",
        "username": "",
        "password": null,
        "email": "sudhafgar@yopmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14070,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "ffd",
        "username": "",
        "password": null,
        "email": "suwwwrajK@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14097,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "supereeadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14075,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "superadmin@gmail.com",
        "phonenumber": "11111111111111111111",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14100,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "supuuueradmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14111,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "jadgaleeassa",
        "username": "",
        "password": null,
        "email": "superaaaaaaadmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14112,
        "prefix": null,
        "firstname": "ttryyuyt",
        "middlename": "",
        "lastname": "fsfdsdsf",
        "username": "",
        "password": null,
        "email": "superaiuiuiudmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 43,
        "prefix": null,
        "firstname": "Tyshawn",
        "middlename": "a",
        "lastname": "Padberg",
        "username": "Pietro_Langworth",
        "password": null,
        "email": "Ana.Funk@gmail.com",
        "phonenumber": "7387943948",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/foczzi_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13971,
        "prefix": null,
        "firstname": "Uma",
        "middlename": "",
        "lastname": "kuresi",
        "username": "",
        "password": null,
        "email": "uma@gmail.com",
        "phonenumber": "4372682349",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13972,
        "prefix": null,
        "firstname": "Uma",
        "middlename": "",
        "lastname": "kurasi",
        "username": "",
        "password": null,
        "email": "uma2@gmail.com",
        "phonenumber": "38293102",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 40,
        "prefix": null,
        "firstname": "Vanessa",
        "middlename": "c",
        "lastname": "Collier",
        "username": "Ignatius_Huel62",
        "password": null,
        "email": "Jordyn_Kuhn31@yahoo.com",
        "phonenumber": "8828731874",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/bargaorobalo_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14057,
        "prefix": null,
        "firstname": "venkata",
        "middlename": "",
        "lastname": "kota",
        "username": "",
        "password": null,
        "email": "srl_mum@hotmail.com",
        "phonenumber": "12032789490",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 74,
        "prefix": null,
        "firstname": "Virgil",
        "middlename": "c",
        "lastname": "Mante",
        "username": "Charles26",
        "password": null,
        "email": "Lavina67@yahoo.com",
        "phonenumber": "7651501545",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/joelhelin_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14043,
        "prefix": null,
        "firstname": "William",
        "middlename": "",
        "lastname": "Shakespeare",
        "username": "",
        "password": null,
        "email": "ws@gmail.com",
        "phonenumber": "6382739182",
        "userroleid": 3,
        "rolename": "Candidate",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 60,
        "prefix": null,
        "firstname": "Wilma",
        "middlename": "c",
        "lastname": "Rodriguez",
        "username": "Braden.OKeefe",
        "password": null,
        "email": "Naomi_Dietrich49@yahoo.com",
        "phonenumber": "7433656315",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/brajeshwar_128.jpg",
        "profileFile": null
      },
      {
        "userId": 14084,
        "prefix": null,
        "firstname": "www",
        "middlename": "",
        "lastname": "www",
        "username": "",
        "password": null,
        "email": "supewqeradmin@gmail.com",
        "phonenumber": "21334355",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 75,
        "prefix": null,
        "firstname": "Yolanda",
        "middlename": "b",
        "lastname": "Kohler",
        "username": "Reuben_Kerluke",
        "password": null,
        "email": "Lillian59@gmail.com",
        "phonenumber": "9206140692",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/kevinoh_128.jpg",
        "profileFile": null
      },
      {
        "userId": 13967,
        "prefix": null,
        "firstname": "zala",
        "middlename": "",
        "lastname": "leon",
        "username": "",
        "password": null,
        "email": "zala@gmail.com",
        "phonenumber": "6576745357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 13966,
        "prefix": null,
        "firstname": "Zebar",
        "middlename": "",
        "lastname": "phon",
        "username": "",
        "password": null,
        "email": "zebar@gmail.com",
        "phonenumber": "09877645357",
        "userroleid": 2,
        "rolename": "Customer",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": null,
        "profileFile": null
      },
      {
        "userId": 14,
        "prefix": null,
        "firstname": "Zoila",
        "middlename": "a",
        "lastname": "Miller",
        "username": "Corene20",
        "password": null,
        "email": "Kellie.Oberbrunner43@gmail.com",
        "phonenumber": "7127241792",
        "userroleid": 1,
        "rolename": "Admin",
        "isactive": true,
        "currentUserId": null,
        "profilephotopath": "https://cdn.fakercloud.com/avatars/antongenkin_128.jpg",
        "profileFile": null
      }
    ],
    "totalRows": 173
  },
  "status": "Success",
  "message": "Users get API requested"
}