export const candidateList = [
    {
        jobapplicationid: 117,
        candidateid: 34,
        title: "React JS developer",
        firstname: "Brando",
        lastname: "Green",
        dob: "2023-09-04T00:00:00",
        email: "Houston.Denesik@gmail.com",
        phonenumber: "8168055198",
        description:"Aasrtedfghyt",
        address: "19005 Theresa Coves",
        zipcode: "12441",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Houston.Denesik@gmail.com",
        experienceyears: 9,
        primaryskills: "Java",
        secondaryskills: "C++,Python,Java,PHP,C#,PHP,Pearl,Ruby",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/anoff_128.jpg",
        resumefile: null,
        applicationdate: "2023-09-04T12:08:09.497",
        applicationstatus: "Applied",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 3,
        isrelocate: true,
        isvideoconference: false,
        noticeperiod: "3 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 43,
        candidateid: 8,
        firstname: "AA",
        lastname: "SS",
        title: "Angular developer",
        dob: "2002-08-11T00:00:00",
        email: "aass@gmail.com",
        description:"Axxxxxrtedfghyt",
        phonenumber: "2372328939",
        address: "AA road",
        zipcode: "123654",
        cityname: "Sitka",
        statename: "Alaska",
        regionname: null,
        countryname: "US",
        summary: "nothing",
        experienceyears: 3,
        primaryskills: "developer",
        secondaryskills: "frontend",
        profilephotopath: null,
        resumepath:
            "https://sadeveastusa001.blob.core.windows.net/cndev001/Candidate/10/Resume/Sydney-Resume-Template-Modern.pdf",
        resumefile: null,
        applicationdate: "2023-08-29T14:50:39.587",
        applicationstatus: "Rejected",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: true,
        isvideoconference: true,
        noticeperiod: "2 weeks",
        rejectedreasonid: 1,
        rejectionreason: "Missing qualifications",
        rejectedcomment: "Fake candidate",
    },
    {
        jobapplicationid: 37,
        candidateid: 57,
        firstname: "Mittie",
        lastname: "Corwin",
        dob: "2023-09-04T00:00:00",
        title: ".net developer",
        description:"Pppdsrtedfghyt",
        email: "Tremayne60@gmail.com",
        phonenumber: "7611346790",
        address: "681 Jessie Common",
        zipcode: "03192",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Tremayne60@gmail.com",
        experienceyears: 8,
        primaryskills: "Python",
        secondaryskills: "PHP",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/herbigt_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-27T02:53:46.647",
        applicationstatus: "Rejected",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 2,
        rejectionreason: "Employment gaps",
        rejectedcomment: "test",
    },
    {
        jobapplicationid: 26,
        candidateid: 49,
        firstname: "Margaretta",
        lastname: "Sporer",
        dob: "2023-09-04T00:00:00",
        title: "Java developer",
        email: "Laurel_Lakin@yahoo.com",
        phonenumber: "9941839925",
        address: "6687 Douglas Port",
        zipcode: "08197-7255",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Laurel_Lakin@yahoo.com",
        experienceyears: 16,
        primaryskills: "PHP",
        secondaryskills: "C++",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/carlosgavina_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-25T15:05:41.483",
        applicationstatus: "Rejected",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 2,
        rejectionreason: "Employment gaps",
        rejectedcomment: "testing ",
    },
    {
        jobapplicationid: 23,
        candidateid: 18,
        firstname: "Marisa",
        lastname: "Rath",
        dob: "2023-09-04T00:00:00",
        email: "Macey_Langworth@gmail.com",
        phonenumber: "9515161455",
        address: "8320 Erdman Way",
        zipcode: "71698",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Macey_Langworth@gmail.com",
        experienceyears: 2,
        primaryskills: "C# .Net",
        secondaryskills: "C++,Python,Java,PHP,C#,",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/aaronkwhite_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-25T14:56:57.793",
        applicationstatus: "Rejected",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 1,
        rejectionreason: "Missing qualifications",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 237,
        candidateid: 35,
        firstname: "Brando",
        lastname: "Green",
        dob: "2023-09-04T00:00:00",
        email: "Houston.Denesik@gmail.com",
        phonenumber: "8168055198",
        address: "19005 Theresa Coves",
        zipcode: "12441",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Houston.Denesik@gmail.com",
        experienceyears: 9,
        primaryskills: "Java",
        secondaryskills: "C++,Python,Java,PHP,C#,PHP,Pearl,Ruby",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/anoff_128.jpg",
        resumefile: null,
        applicationdate: "2023-09-14T08:02:28.097",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: true,
        isvideoconference: true,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 211,
        candidateid: 35,
        firstname: "Brando",
        lastname: "Green",
        dob: "2023-09-04T00:00:00",
        email: "Houston.Denesik@gmail.com",
        phonenumber: "8168055198",
        address: "19005 Theresa Coves",
        zipcode: "12441",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Houston.Denesik@gmail.com",
        experienceyears: 9,
        primaryskills: "Java",
        secondaryskills: "C++,Python,Java,PHP,C#,PHP,Pearl,Ruby",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/anoff_128.jpg",
        resumefile: null,
        applicationdate: "2023-09-11T15:26:44.057",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 1,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "1 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 202,
        candidateid: 35,
        firstname: "Brando",
        lastname: "Green",
        dob: "2023-09-04T00:00:00",
        email: "Houston.Denesik@gmail.com",
        phonenumber: "8168055198",
        address: "19005 Theresa Coves",
        zipcode: "12441",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Houston.Denesik@gmail.com",
        experienceyears: 9,
        primaryskills: "Java",
        secondaryskills: "C++,Python,Java,PHP,C#,PHP,Pearl,Ruby",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/anoff_128.jpg",
        resumefile: null,
        applicationdate: "2023-09-11T09:31:14.087",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 4,
        isrelocate: true,
        isvideoconference: true,
        noticeperiod: "More than 3 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 118,
        candidateid: 34,
        firstname: "Brando",
        lastname: "Green",
        dob: "2023-09-04T00:00:00",
        email: "Houston.Denesik@gmail.com",
        phonenumber: "8168055198",
        address: "19005 Theresa Coves",
        zipcode: "12441",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Houston.Denesik@gmail.com",
        experienceyears: 9,
        primaryskills: "Java",
        secondaryskills: "C++,Python,Java,PHP,C#,PHP,Pearl,Ruby",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/anoff_128.jpg",
        resumefile: null,
        applicationdate: "2023-09-04T12:08:09.497",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 3,
        isrelocate: true,
        isvideoconference: false,
        noticeperiod: "3 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 57,
        candidateid: 4,
        firstname: "BB",
        lastname: "JJ",
        dob: "2000-12-12T00:00:00",
        email: "jj@gmail.com",
        phonenumber: "3245546777",
        address: "jj road, Pune",
        zipcode: "765345",
        cityname: "Birmingham",
        statename: "Alabama",
        regionname: null,
        countryname: "US",
        summary: "Need new job",
        experienceyears: 4,
        primaryskills: "Software developer",
        secondaryskills: "frontend, backend",
        profilephotopath: null,
        resumepath:
            "https://sadeveastusa001.blob.core.windows.net/cndev001/Candidate/4/Resume/Stockholm-Resume-Template-Simple.pdf",
        resumefile: null,
        applicationdate: "2023-09-01T13:25:19.51",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 4,
        isrelocate: true,
        isvideoconference: true,
        noticeperiod: "More than 3 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 42,
        candidateid: 8,
        firstname: "AA",
        lastname: "SS",
        dob: "2002-08-11T00:00:00",
        email: "aass@gmail.com",
        phonenumber: "2372328939",
        address: "AA road",
        zipcode: "123654",
        cityname: "Sitka",
        statename: "Alaska",
        regionname: null,
        countryname: "US",
        summary: "nothing",
        experienceyears: 3,
        primaryskills: "developer",
        secondaryskills: "frontend",
        profilephotopath: null,
        resumepath:
            "https://sadeveastusa001.blob.core.windows.net/cndev001/Candidate/10/Resume/Sydney-Resume-Template-Modern.pdf",
        resumefile: null,
        applicationdate: "2023-08-27T06:17:25.2",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 41,
        candidateid: 8,
        firstname: "AA",
        lastname: "SS",
        dob: "2002-08-11T00:00:00",
        email: "aass@gmail.com",
        phonenumber: "2372328939",
        address: "AA road",
        zipcode: "123654",
        cityname: "Sitka",
        statename: "Alaska",
        regionname: null,
        countryname: "US",
        summary: "nothing",
        experienceyears: 3,
        primaryskills: "developer",
        secondaryskills: "frontend",
        profilephotopath: null,
        resumepath:
            "https://sadeveastusa001.blob.core.windows.net/cndev001/Candidate/10/Resume/Sydney-Resume-Template-Modern.pdf",
        resumefile: null,
        applicationdate: "2023-08-27T03:07:32.017",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 40,
        candidateid: 60,
        firstname: "Lazaro",
        lastname: "Casper",
        dob: "2023-09-04T00:00:00",
        email: "Jamar45@gmail.com",
        phonenumber: "7386093947",
        address: "96506 Considine Plain",
        zipcode: "67991-1130",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Jamar45@gmail.com",
        experienceyears: 1,
        primaryskills: "Python",
        secondaryskills: "PHP",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/hafeeskhan_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-27T03:07:15.53",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 39,
        candidateid: 59,
        firstname: "Darron",
        lastname: "Schuppe",
        dob: "2023-09-04T00:00:00",
        email: "Esperanza_Bradtke69@gmail.com",
        phonenumber: "9115026440",
        address: "22443 Rodriguez Stravenue",
        zipcode: "23935-2077",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Esperanza_Bradtke69@gmail.com",
        experienceyears: 17,
        primaryskills: "C++",
        secondaryskills: "C# .Net",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/moynihan_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-27T03:05:11.493",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
    {
        jobapplicationid: 38,
        candidateid: 58,
        firstname: "Darron",
        lastname: "Schuppe",
        dob: "2023-09-04T00:00:00",
        email: "Esperanza_Bradtke69@gmail.com",
        phonenumber: "9115026440",
        address: "22443 Rodriguez Stravenue",
        zipcode: "23935-2077",
        cityname: null,
        statename: null,
        regionname: null,
        countryname: null,
        summary: "Esperanza_Bradtke69@gmail.com",
        experienceyears: 17,
        primaryskills: "C++",
        secondaryskills: "C# .Net",
        profilephotopath: null,
        resumepath: "https://cdn.fakercloud.com/avatars/moynihan_128.jpg",
        resumefile: null,
        applicationdate: "2023-08-27T03:01:33.243",
        applicationstatus: "Accepted",
        feedback: null,
        ratings: null,
        skills: null,
        noticeperiodid: 2,
        isrelocate: false,
        isvideoconference: false,
        noticeperiod: "2 weeks",
        rejectedreasonid: 0,
        rejectionreason: "",
        rejectedcomment: "",
    },
];
